name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: "pandoc -s -o docs/readme.rst docs/index.md" # gets appended to pandoc command
# pandoc docs/index.md --from markdown --to rst -s -o readme.rst
