name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: docs/index.md
      - uses: docker://pandoc/core:2.9
        with:
          args: "pandoc docs/index.md --from markdown --to rst -s -o readme.rst" # gets appended to pandoc command
# pandoc docs/index.md --from markdown --to rst -s -o readme.rst
